[workspace]
members = ["zingolib-ffi"]
resolver = "2"

[workspace.dependencies]
zingolib = { git = "https://github.com/zingolabs/zingolib", default-features = true, branch = "dev", features = [
    "test-elevation",
] }
zcash_primitives = "0.22.0"
