[workspace]
members = ["zingolib-ffi"]
resolver = "2"

[workspace.dependencies]
zingolib = { git = "https://github.com/zingolabs/zingolib", default-features = true, tag = "1.11.0", features = [
    "test-elevation",
] }
